version: '3.8'
  
services:
  
  ingest-daemon:
    container_name: ingest-daemon
    image: pinecni/ingest-daemon:latest
    hostname: ingest-daemon
    ports:
      - 9888:8888
    volumes:
      - ./logs:/opt/logs:Z  
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://211.189.131.71:5432/ingest
      - DATASOURCE_ID=smartcity
      - DATASOURCE_PW=nb1234
      - INGEST_INTERFACE_API_USE_YN=Y
      - INGEST_INTERFACE_API_URL=http://211.189.131.71:8081/entityOperations/upsert?options=update
      - LOG_LEVEL=info
    restart: always

  ingest-web:
    container_name: ingest-web
    image: pinecni/ingest-web:latest 
    hostname: ingest-web
    ports:
      - 9080:8080
    volumes:
      - ./logs:/opt/logs:Z        
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://211.189.131.71:5432/ingest
      - DATASOURCE_ID=smartcity
      - DATASOURCE_PW=nb1234
      - DAEMON_URL=http://ingest-daemon:8888
      - DATAMODEL_API_URL=http://211.189.131.71:8080/datamodels
      - INGEST_INTERFACE_API_USE_YN=Y
      - INGEST_INTERFACE_API_URL=http://211.189.131.71:8081/entityOperations/upsert?options=update
      - AUTH_YN=Y
      - AUTH_EXTERNAL_URL=http://211.189.131.71:40000
      - AUTH_INTERNAL_URL=http://211.189.131.71:40000
      - AUTH_CLIENT_ID=DRJr9Fw5Lt3yd8KrCnOm
      - AUTH_CLIENT_SECRET=rA9xiKK3vrciSZJvnQofdc6r95MjSDtu
      - AUTH_REDIRECT_URL=http://211.189.131.71:9080/accesstoken
      - EUREKA_ENABLED=false
      - EUREKA_EUREKA_DEFAULT_ZONE=http://211.189.131.71:18888/eureka
      - LOG_LEVEL=info
    depends_on:
      ingest-daemon:
        condition: service_started     
    restart: always   

