version: "3.8"

services: 
  apigw:
    build: ./
    image: apigw
    ports:
      - 28888:28888
    volumes:
      - ./logs:/logs
    environment:
      - TZ=Asia/Seoul
      - SERVER_PORT=28888
      - EUREKA_DEFAULT_ZONE=http://211.189.131.71:18888/eureka
      - REDIS_HOST=211.189.131.71
      - DATASOURCE_URL= jdbc:postgresql://211.189.131.71:5432/apigw
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=nb1234
      - CITYHUB_CLIENT_PUBLICKEYURI=http://211.189.131.71:40000/security/publickey
    restart: always

  # datacore ----------------------------------
  zookeeper:
    image: confluentinc/cp-zookeeper:6.0.0
    tmpfs: /tmp
    restart: always
    ports:
      - 2181:2181
    environment:
      TZ: Asia/Seoul
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.0.0
    ports:
      - 29092:29092
      - 9092:9092
      # - 9101:9101
    restart: always
    environment:
      TZ: Asia/Seoul
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      # KAFKA_JMX_PORT: 9101
      # KAFKA_JMX_HOSTNAME: localhost
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      zookeeper:
        condition: service_started

  rest-proxy:
    image: confluentinc/cp-kafka-rest:6.0.0
    ports:
      - 18082:8082
    environment:
      TZ: Asia/Seoul
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: broker:29092
      KAFKA_REST_LISTENERS: http://0.0.0.0:8082
    depends_on:
      broker:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
    volumes:
      - ./plugins.erl:/etc/rabbitmq/enabled_plugins
    environment:
      TZ: Asia/Seoul
      RABBITMQ_ERLANG_COOKIE: RabbitMQ-My-Cookies
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin


  data-manager:
    image: keti/sc/data-manager
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./logs/data-manager:/logs
    environment:
      TZ: Asia/Seoul
      DATASOURCE_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_USERNAME: "smartcity"
      DATASOURCE_PASSWORD: "nb1234"
      DATASOURCE_SECONDARY_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_SECONDARY_USERNAME: "smartcity"
      DATASOURCE_SECONDARY_PASSWORD: "nb1234"
      KAFKA_SECURITY_YN: "N"
      KAFKA_URL: broker:29092
      EUREKA_CLIENT_ENABLED: false
      EUREKA_INSTANCE_HOSTNAME: 211.189.131.71
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://211.189.131.71:18888/eureka
      REST_PROXY_URL: http://rest-proxy:8082
      SECURITY_ACL_USEYN: "N"
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started


  ingest-interface:
    image: keti/sc/ingest-interface
    restart: always
    ports:
      - 8081:8081
      - 443:443
    volumes:
      - ./logs/ingest-interface:/logs
    environment:
      TZ: Asia/Seoul
      DATASOURCE_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_USERNAME: "smartcity"
      DATASOURCE_PASSWORD: "nb1234"
      DATASOURCE_SECONDARY_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_SECONDARY_USERNAME: "smartcity"
      DATASOURCE_SECONDARY_PASSWORD: "nb1234"
      KAFKA_SECURITY_YN: "N"
      KAFKA_URL: broker:29092
      EUREKA_CLIENT_ENABLED: false
      EUREKA_INSTANCE_HOSTNAME: 211.189.131.71
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://211.189.131.71:18888/eureka
      SECURITY_ACL_USEYN: "N"
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started


  data-service-broker:
    image: keti/sc/data-service-broker
    restart: always
    ports:
      - 8082:8082
    volumes:
      - ./logs/data-service-broker:/logs
    environment:
      TZ: Asia/Seoul
      DATASOURCE_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_USERNAME: "smartcity"
      DATASOURCE_PASSWORD: "nb1234"
      DATASOURCE_SECONDARY_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_SECONDARY_USERNAME: "smartcity"
      DATASOURCE_SECONDARY_PASSWORD: "nb1234"
      KAFKA_SECURITY_YN: "N"
      KAFKA_URL: broker:29092
      EUREKA_CLIENT_ENABLED: false
      EUREKA_INSTANCE_HOSTNAME: 211.189.131.71
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://211.189.131.71:18888/eureka
      SPRING_SECURITY_ENABLED: false
      SECURITY_ACL_USEYN: "N"
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started


  datacore-ui:
    image: keti/sc/datacore-ui
    restart: always
    ports:
      - 8083:8083
    volumes:
      - ./logs/datacore-ui:/logs
    environment:
      TZ: Asia/Seoul
      DATASOURCE_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_USERNAME: "smartcity"
      DATASOURCE_PASSWORD: "nb1234"
      DATASOURCE_SECONDARY_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_SECONDARY_USERNAME: "smartcity"
      DATAMANAGER_URL: http://data-manager:8080
      INGESTINTERFACE_URL: http://ingest-interface:8081
      DATASOURCE_SECONDARY_PASSWORD: "nb1234"
      SPRING_SECURITY_ENABLED: true
      CITYHUB_CLIENT_CLIENTID: kU0qMygHzVTIrXO2fjMv
      CITYHUB_CLIENT_CLIENTSECRET: YhDpMuWZLGVgT7XfKUsHj91qAnBQREZd
      CITYHUB_CLIENT_ACCESSTOKENURI: http://211.189.131.71:40000/oauth2.0/token
      CITYHUB_CLIENT_USERAUTHORIZATIONURI: http://211.189.131.71:40000/oauth2.0/authorize
      CITYHUB_CLIENT_PUBLICKEYURI: http://211.189.131.71:40000/security/publickey
      CITYHUB_CLIENT_LOGOUTURI: http://211.189.131.71:40000/security/logout
      CITYHUB_CLIENT_USERINFOURI: http://211.189.131.71:40000/security/users
      CITYHUB_CLIENT_REDIRECTURI: http://211.189.131.71:8083/accesstoken
      EUREKA_CLIENT_ENABLED: false
      EUREKA_INSTANCE_HOSTNAME: 211.189.131.71
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://211.189.131.71:18888/eureka
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started


  datacore-dashboard:
    image: keti/sc/datacore-usertool
    restart: always
    ports:
      - 8084:8084
    volumes:
      - ./logs/datacore-usertool:/logs
    environment:
      TZ: Asia/Seoul
      DATASOURCE_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_USERNAME: "smartcity"
      DATASOURCE_PASSWORD: "nb1234"
      DATASOURCE_SECONDARY_URL: jdbc:postgresql://211.189.131.71:5432/datacore
      DATASOURCE_SECONDARY_USERNAME: "smartcity"
      DATASOURCE_SECONDARY_PASSWORD: "nb1234"
      DATAMANAGER_URL: http://data-manager:8080
      INGESTINTERFACE_URL: http://ingest-interface:8081
      SPRING_SECURITY_ENABLED: true
      CITYHUB_CLIENT_CLIENTID: yK4Cm8DKHJZOCDoS3hjz
      CITYHUB_CLIENT_CLIENTSECRET: Qj7FwPVTcmULqzGqLrLj0RNqJXsQ9QQJ
      CITYHUB_CLIENT_REDIRECTURI: http://211.189.131.71:8084/accesstoken
      CITYHUB_CLIENT_USERAUTHORIZATIONURI: http://211.189.131.71:40000/oauth2.0/authorize
      CITYHUB_CLIENT_ACCESSTOKENURI: http://211.189.131.71:40000/oauth2.0/token
      CITYHUB_CLIENT_PUBLICKEYURI: http://211.189.131.71:40000/security/publickey
      CITYHUB_CLIENT_LOGOUTURI: http://211.189.131.71:40000/security/logout
      CITYHUB_CLIENT_USERINFOURI: http://211.189.131.71:40000/security/users
      GOOGLE_API_KEY: XXXXXXXXXXXXXXXXXXX-XXX_XXXXXXXXXXXXXXX
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started


  push-agent:
    image: keti/sc/push-agent
    restart: always
    volumes:
      - ./logs/push-agent:/logs
    environment:
      TZ: Asia/Seoul
      KAFKA_SECURITY_YN: "N"
      KAFKA_URL: broker:29092
      JVM_OPTS: -Xmx2048m -Xms2048m
    depends_on:
      broker:
        condition: service_started
      rest-proxy:
        condition: service_started
  # datacore ----------------------------------

  eureka-server:
    build: ./
    image: server
    ports:
      - 18888:18888
    volumes:
      - ./logs:/logs
    environment:
      - TZ=Asia/Seoul

  # ingest ----------------------------------
  ingest-daemon:
    container_name: ingest-daemon
    image: pinecni/ingest-daemon:latest
    hostname: ingest-daemon
    ports:
      - 9888:8888
    volumes:
      - ./logs:/opt/logs:Z  
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://211.189.131.71:5432/ingest
      - DATASOURCE_ID=smartcity
      - DATASOURCE_PW=nb1234
      - INGEST_INTERFACE_API_USE_YN=Y
      - INGEST_INTERFACE_API_URL=http://211.189.131.71:8081/entityOperations/upsert?options=update
      - LOG_LEVEL=info
    restart: always

  ingest-web:
    container_name: ingest-web
    image: pinecni/ingest-web:latest 
    hostname: ingest-web
    ports:
      - 9080:8080
    volumes:
      - ./logs:/opt/logs:Z        
    environment:
      - TZ=Asia/Seoul
      - DATASOURCE_DRIVER=org.postgresql.Driver
      - DATASOURCE_URL=jdbc:postgresql://211.189.131.71:5432/ingest
      - DATASOURCE_ID=smartcity
      - DATASOURCE_PW=nb1234
      - DAEMON_URL=http://ingest-daemon:8888
      - DATAMODEL_API_URL=http://211.189.131.71:8080/datamodels
      - INGEST_INTERFACE_API_USE_YN=Y
      - INGEST_INTERFACE_API_URL=http://211.189.131.71:8081/entityOperations/upsert?options=update
      - AUTH_YN=Y
      - AUTH_EXTERNAL_URL=http://211.189.131.71:40000
      - AUTH_INTERNAL_URL=http://211.189.131.71:40000
      - AUTH_CLIENT_ID=DRJr9Fw5Lt3yd8KrCnOm
      - AUTH_CLIENT_SECRET=rA9xiKK3vrciSZJvnQofdc6r95MjSDtu
      - AUTH_REDIRECT_URL=http://211.189.131.71:9080/accesstoken
      - EUREKA_ENABLED=false
      - EUREKA_EUREKA_DEFAULT_ZONE=http://211.189.131.71:18888/eureka
      - LOG_LEVEL=info
    depends_on:
      ingest-daemon:
        condition: service_started     
    restart: always
  # ingest ----------------------------------

  db:
    build: ./
    image: postgresql
    container_name: pgsql
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nb1234
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale=ko_KR.utf8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  redis_container:
    image: redis:latest
    container_name: redis_chungnam
    ports:
      - 6379:6379
    volumes:
      - ./redis/data:/data
      - ./redis/conf/redis.conf:/usr/local/conf/redis.conf
    labels:
      - "name=redis"
      - "mode=standalone"
    restart: always
    command: redis-server /usr/local/conf/redis.conf

  # security/admin ----------------------------------
  security_back_admin:
    build: ./smartcity_back
    image: security_back_admin
    container_name: security_back_admin
    ports:
      - 30000:30000
    volumes:
      - ./logs/back:/logs
    environment:
      - TZ=Asia/Seoul
    restart: always

  security_front_admin:
    build: ./smartcity_front
    image: security_front_admin
    container_name: security_front_admin
    ports:
      - 30001:30001
    volumes:
      - ./logs/front:/logs
    environment:
      - TZ=Asia/Seoul
    restart: always
  # security/admin ----------------------------------

  # security/user ----------------------------------
  security_back_user:
    build: ./smartcity_back
    image: security_back_user
    container_name: security_back_user
    ports:
      - 40000:40000
    volumes:
      - ./logs/back:/logs
    environment:
      - TZ=Asia/Seoul
    restart: always

  security_front_user:
    build: ./smartcity_front
    image: security_front_user
    container_name: security_front_user
    ports:
      - 40001:40001
    volumes:
      - ./logs/front:/logs
    environment:
      - TZ=Asia/Seoul
    restart: always
  # security/user ----------------------------------

volumes:
  pgdata:

networks:
  default:
    name: citydatahub-datacore
    external: true