version: '3.8'
services:
  db:
    build: ./
    image: postgresql
    container_name: pgsql
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: nb1234
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: "--locale=ko_KR.utf8"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
volumes:
  pgdata:
